# Generated by Django 5.2.4 on 2025-09-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0002_alter_result_time_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='fa_icon',
            field=models.CharField(default='fas fa-question', help_text="Font Awesome class, e.g., 'fas fa-laptop', 'fab fa-python'", max_length=50),
        ),
    ]
